# Marp CLI設定ファイル

themeSet:
  - ./theme/marp-theme-digion.css
  - https://raw.githubusercontent.com/takasumi-iwamoto-digion/marp-digion-template/main/theme/marp-theme-digion.css

# デフォルトオプション
options:
  html: true
  pdf: true
  
# ローカル画像を使用する場合はコメントを外してください
# allowLocalFiles: true