# Marp CLI設定ファイル

themeSet:
  - ./marp-custom-fixed.css
  - https://raw.githubusercontent.com/takasumi-iwamoto-digion/marp-digion-template/main/marp-custom-fixed.css

# デフォルトオプション
options:
  html: true
  pdf: true